### ISSUE TITLE
Dropdown for low cardinality attributes is no longer working / Can't add filter after running a query

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Arronax#152]
Discovered these two bugs in `develop`. See below gif.

![arronax-bugs](https://user-images.githubusercontent.com/37525692/55890905-9201a180-5b81-11e9-9a3e-fdc9ae6831ab.gif)

**Comment by Sm00g15** [comment]
fixed in PR #151

**Comment by umurb** [comment]
I am currently checking PR#151. The dropdown is now working, but I still can't add filters after running a query.

**Comment by umurb** [comment]
Consider implementing https://github.com/Cryptonomic/Arronax/issues/156 to fix this bug

**Comment by Sm00g15** [comment]
Joe's implemented this in PR #157

**Comment by umurb** [comment]
Fixed with #157
